// <auto-generated />
using CoreApp1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreApp1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190606071706_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreApp1.Models.Course", b =>
                {
                    b.Property<int>("CourseRowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Capacity");

                    b.Property<string>("CourseId")
                        .IsRequired();

                    b.Property<string>("CourseName")
                        .IsRequired();

                    b.HasKey("CourseRowId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CoreApp1.Models.Student", b =>
                {
                    b.Property<int>("StudentRowId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<int>("CourseRowId");

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("StudentId")
                        .IsRequired();

                    b.Property<string>("StudentName")
                        .IsRequired();

                    b.HasKey("StudentRowId");

                    b.HasIndex("CourseRowId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoreApp1.Models.Student", b =>
                {
                    b.HasOne("CoreApp1.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseRowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
